* Draft: 2020-09-09 (Wed)

In [6]:
# Create sequences like [0.0, 0.1, 0.2, 0.3], [0.1, 0.2, 0.3, 0.4], ... [0.6, 0.7, 0.8, 0.9]

list_of_input_sequences = []
list_of_output_sequence = []

for i in range(6):
    # Create a sequence like [0,1,2,3], [1,2,3,4], ... [6,7,8,9]
    sequence = list( range( i,i+4 ) )
    
    list_of_input_sequences.append( list( map( lambda c: [c/10], sequence)) )  # divide by 10
    list_of_output_sequence.append( (i+4)/10 )

In [7]:
import numpy as np

x_np = np.array( list_of_input_sequences )
y_np = np.array( list_of_output_sequence )

In [10]:
for i in range( len(x_np) ):
    print( x_np[i], y_np[i] )

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9


## Create a SimpleRNN model

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN( units=10, return_sequences=False, input_shape=[4,1] ),
    tf.keras.layers.Dense(1)
])
model.compile( optimizer='adam', loss='mse' )
model.summary()

input_shape=[4,1]는 timesteps=4, input_dim=1입니다.
* timesteps은 RNN이 입력에 대한 계산을 반복하는 횟수입니다.
* input_dim은 입력의 차원, 즉 입력벡터의 크기입니다.

In [14]:
x_np.shape

(6, 4, 1)

6개의 4x1차원의 sequence가 있으므로 timesteps=4, input_dim=1이 됩니다.

Dense(1)는 별도로 activation function이 없으므로 SimpleRNN의 출력 h3이 바로 y3가 됩니다.

## 모델 훈련

In [15]:
model.fit( x_np, y_np, epochs=100, verbose=0 )
model.predict( x_np )

array([[0.3655806 ],
       [0.49643004],
       [0.61437166],
       [0.71791565],
       [0.8074425 ],
       [0.8842804 ]], dtype=float32)

## 예측하기

In [17]:
sequence= [[[0.6],[0.7],[0.8],[0.9]]]
model.predict( np.array( sequence ))

array([[0.95000964]], dtype=float32)

In [18]:
sequence= [[[-0.1],[0.0],[0.1],[0.2]]]
model.predict( np.array( sequence ))

array([[0.22574158]], dtype=float32)